---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: microservices
type: Opaque
stringData:
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: microservices
type: Opaque
stringData:
  RABBITMQ_USER: "admin"
  RABBITMQ_PASSWORD: "admin"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: microservices
type: Opaque
stringData:
  POSTGRES_USER: "authuser"
  POSTGRES_PASSWORD: "authpassword"
  POSTGRES_DB: "authdb"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth-secret
  namespace: microservices
type: Opaque
stringData:
  REDIS_PASSWORD: "redispassword"

---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: microservices
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "citizen_affiliation"
  MYSQL_USER: "djangouser"
  MYSQL_PASSWORD: "djangopass"

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: microservices
type: Opaque
stringData:
  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "admin123"

---
apiVersion: v1
kind: Secret
metadata:
  name: dynamodb-secret
  namespace: microservices
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "admin"
  AWS_SECRET_ACCESS_KEY: "admin123"
  AWS_REGION: "us-east-1"

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: microservices
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "admin"
