# Generated by Django 5.0.6 on 2025-11-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentauthentication',
            name='message_id',
            field=models.CharField(blank=True, default='', help_text='Message ID for deduplication', max_length=100),
        ),
        migrations.AddField(
            model_name='documentauthentication',
            name='document_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Document ID from Documents microservice', max_length=100),
        ),
    ]
